spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:  #Google mail , google account 2nd authentication must opened..
    password:  #Google app password
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false
  profiles:
    active:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
app:
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret : sBnlg0BGosgPMQju
  routes:
    user:
      addBalance: /add-balance
    auth:
      createUser: /create-user
      authUser: /auth-user
#    feignClient:
#      name: UserServiceClient
#      url:
logging:
  level:
    org.springframework: DEBUG

